# Generated by Django 4.1.4 on 2022-12-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorie",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="categorie",
            name="subject",
            field=models.CharField(max_length=100),
        ),
    ]
