# Generated by Django 4.1.4 on 2022-12-13 21:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Categories",
            new_name="Categorie",
        ),
    ]
