# Generated by Django 4.1.4 on 2022-12-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="img",
            field=models.URLField(null=True),
        ),
    ]
